export const GET_ACTIVITIES_LIST = 'GET_ACTIVITIES_LIST'
export const GET_ACTIVITIES_LIST_SUCCESS = 'GET_ACTIVITIES_LIST_SUCCESS'
export const GET_ACTIVITIES_LIST_FAIL = 'GET_ACTIVITIES_LIST_FAIL'

export const GET_ACTIVITY_INFO = 'GET_ACTIVITY_INFO'
export const GET_ACTIVITY_INFO_SUCCESS = 'GET_ACTIVITY_INFO_SUCCESS'
export const GET_ACTIVITY_INFO_FAIL = 'GET_ACTIVITY_INFO_FAIL'

export const ARCHIVE_ACTIVITY = 'ARCHIVE_ACTIVITY'
export const ARCHIVE_ACTIVITY_SUCCESS = 'ARCHIVE_ACTIVITY_SUCCESS'
export const ARCHIVE_ACTIVITY_FAIL = 'ARCHIVE_ACTIVITY_FAIL'

export const RESTORE_ACTIVITY = 'RESTORE_ACTIVITY'
export const RESTORE_ACTIVITY_SUCCESS = 'RESTORE_ACTIVITY_SUCCESS'
export const RESTORE_ACTIVITY_FAIL = 'RESTORE_ACTIVITY_FAIL'
